steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/pixvie-be', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'eu.gcr.io/$PROJECT_ID/pixvie-be']
- name: "gcr.io/cloud-builders/git"
  args: ['clone', 'https://github.com/Pixvie/pixvie-k8s-infra.git']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --location=europe-west3
  - --cluster=emrullah-cluster-1
  dir: "pixvie-k8s-infra/apps/pixvie-be"
