apiVersion: v1
items:
- apiVersion: v1
  data:
    COOKIE_SECRET: cGl4dmllLWU2Y2NiOGExNjVhMTQ5NzNmYzUwYTliMWUxY2U1ZTA4
    JWT_SECRET: cGl4dmllLWY4MWI2YTYxNzk1ODI1ZmEyMTk0OTgxMTg1ZjhkZDMw
    MONGODB_URI: bW9uZ29kYitzcnY6Ly9waXh2aWU6cGl4dmllQHBpeHZpZS5nMXcwa3gyLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
    PORT: ODA=
  kind: Secret
  metadata:
    name: my-secret
    namespace: default
  type: Opaque
kind: List

