apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: pixvie-be
  name: pixvie-deployment-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.27.2.31
  clusterIPs:
  - 10.27.2.31
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31953
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pixvie-be
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.198.166.105
